export const columns = [
    {title: 'index', dataIndex: 'index' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age'},
    {title: 'address', dataIndex: 'address' },
    {title: 'avatar', dataIndex: 'avatar' },
    {title: 'name',dataIndex: 'name' },
    {title: 'age', dataIndex: 'age' },
    {title: 'address1', dataIndex: 'address' }
];

const list = [];
for (let i = 0; i < 1000000; i++) {
    list.push(
        {index: i, avatar: '🎅🏻',name: 'chuanJianGuo', age: 74, address: 'America'},
    );
}

export const dataSource = list;
